### PR TITLE
feat: contributors sections added, gaming category listed

### PR DESCRIPTION
**Pull request by brupadhyay**
Solved Issue #17 , gaming category has been listed,  🚀  contributors added and the section is responsive

### CODE REVIEW

**Comment by brupadhyay** [comment]
Add "hacktoberfest-accepted" here and to the earlier 3 PRs.

**Comment by kd1729** [comment]
@brupadhyay It has merge conflicts, I will review it tomorrow morning and merge it then.

**Comment by brupadhyay** [comment]
@onlykingKD , because I changed alt text for @primeTanM image link

**Comment by brupadhyay** [comment]
@primeTanM any update? @onlykingKD

**Pull request merged**
